### ISSUE TITLE
python test.py CenterNet-52 --testiter 480000 --split <split>

### ISSUE THREAD

**Issue by lifeiwen** [Duankaiwen/CenterNet#11]
What does this <spilt> stand for?

**Comment by TonightGo** [comment]
--testiter 480000 : the model to be evaluated. default = [CenterNet_dir/cache/nnet/CenterNet-52(or 104)/CenterNet-52_480000.pkl]
--split : the dataset to be evaluated. default = validation ([training, validation, testing]).
--suffix : the postfix of model to be evaluated. For example, if you want to use CenterNet_dir/config/CenterNet-52-multi_scale.json, you can set --suffix equal to multi_scale.

**Comment by lifeiwen** [comment]
I don't know what <split> should be, is it just a picture?Can you give an example of this test command? Thank you！

**Comment by TonightGo** [comment]
> I don't know what should be, is it just a picture?Can you give an example of this test command? Thank you！

python test.py CenterNet-104 --testiter 480000 --split testing
python test.py CenterNet-104 --testiter 480000 --split testing --suffix multi_scale
