### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../data/coco/annotations/instances_testdev2017.json'

### ISSUE THREAD

**Issue by sanfordhsu** [Duankaiwen/CenterNet#12]
Excuse me, the error occurs just like the following, though I unzip the annotation file and the COCO dataset just follow the README.md. Who can tell me the reason?

![微信截图_20190423155918](https://user-images.githubusercontent.com/35886298/56564535-d0b34500-65e0-11e9-88f9-2276a7d9b117.png)

**Comment by sanfordhsu** [comment]
Ok, I got it, closed.

**Comment by msha096** [comment]
> Ok, I got it, closed.

How you figure it out? I met the same problem.

**Comment by sanfordhsu** [comment]
> > Ok, I got it, closed.
> 
> How you figure it out? I met the same problem.

Well, If you use the linux system, you need to change the file path 
from '../data/coco/annotations' to './data/coco/annotations'.

**Comment by msha096** [comment]
> > > Ok, I got it, closed.
> > 
> > 
> > How you figure it out? I met the same problem.
> 
> Well, If you use the linux system, you need to change the file path
> from '../data/coco/annotations' to './data/coco/annotations'.

Yes I found it but I did not find the place to change the file path. Could you please tell me which file should I look at ? Thanks!

**Comment by sanfordhsu** [comment]
> > > > Ok, I got it, closed.
> > > 
> > > 
> > > How you figure it out? I met the same problem.
> > 
> > 
> > Well, If you use the linux system, you need to change the file path
> > from '../data/coco/annotations' to './data/coco/annotations'.
> 
> Yes I found it but I did not find the place to change the file path. Could you please tell me which file should I look at ? Thanks!

In Config file, 'CenterNet-104.json' and 'CenterNet-52.json'

**Comment by msha096** [comment]
> > > > > Ok, I got it, closed.
> > > > 
> > > > 
> > > > How you figure it out? I met the same problem.
> > > 
> > > 
> > > Well, If you use the linux system, you need to change the file path
> > > from '../data/coco/annotations' to './data/coco/annotations'.
> > 
> > 
> > Yes I found it but I did not find the place to change the file path. Could you please tell me which file should I look at ? Thanks!
> 
> In Config file, 'CenterNet-104.json' and 'CenterNet-52.json'

Very appreciate that! Thanks!
