### ISSUE TITLE
after training start...

### ISSUE THREAD

**Issue by chiputao0823** [Duankaiwen/CenterNet#13]
after training start... 0%|                                                | 0/500000 [00:00<?, ?it/s]
what happened?

**Comment by chiputao0823** [comment]
i want to train on voc

**Comment by Duankaiwen** [comment]
@chiputao0823 config/CenterNet-52-multi_scale.json and config/CenterNet-52.json have been updated. We will add VOC dataset in the follow-up work.

**Comment by Dawnlnz** [comment]
I am sorry for bother you, can you use VOC for training now?
