### ISSUE TITLE
what's this mean in the file ./test/coco.py? 

### ISSUE THREAD

**Issue by TonightGo** [Duankaiwen/CenterNet#14]
149         if scale == 1:
   150             center_points.append(center)
   151         detections.append(dets)

Why execute line 150 only when scale == 1?

**Comment by Duankaiwen** [comment]
For the multi-scale testing, we only use the detecting results of center keypoints with scale == 1, it's enough.

**Comment by TonightGo** [comment]
I set test_scale to [0.6, 1, 1.2, 1.5, 1.8].  The GPU report out of memory error when inference the picture with scale 1. So I update test_scale with [0.6, 08]. Do you mean I can use "if scale == 0.6" or "if scale == 0.8" instead? What will happen if I comment this line?

**Comment by Duankaiwen** [comment]
Yes, you can use "if scale == 0.6" or "if scale == 0.8" , the center keypoint will be detected under the scale == 0.6 or scale == 0.8.
