### ISSUE TITLE
fault with "python setup.py install --user"

### ISSUE THREAD

**Issue by wudi00** [Duankaiwen/CenterNet#17]
Thank you for your work and code. I have some faults when compile C++ file using "python setup.py install --user", like followings: 
/opt/anaconda3/envs/py36/lib/python3.6/site-packages/torch/lib/include/torch/csrc/variable_tensor_functions.h:35:52  note: declared here
 AT_DEPRECATED(THP_CLASS at::TypeExtendedInterface& CUDA(at::ScalarType type));
                                                    ^
/opt/anaconda3/envs/py36/lib/python3.6/site-packages/torch/lib/include/ATen/core/Deprecated.h:9:61: note: in definition of macro 'AT_DEPRECATED'
 #define AT_DEPRECATED(function) __attribute__((deprecated)) function
                                                             ^~~~~~~~
src/top_pool.cpp:57:44: error: could not convert 'torch::CUDA((c10::ScalarType)0)' from 'at::TypeExtendedInterface' to 'c10::IntList {aka c10::ArrayRef<long int>}'
     auto gt_mask    = at::zeros(torch::CUDA(at::kByte),  {batch, channel, width});
                                 ~~~~~~~~~~~^~~~~~~~~~~
src/top_pool.cpp:58:40: warning: 'at::TypeExtendedInterface& torch::CUDA(c10::ScalarType)' is deprecated [-Wdeprecated-declarations]
     auto max_temp   = at::zeros(torch::CUDA(at::kFloat), {batch, channel, width});


it just a part of the faults, Can you give me some advice to solve this problem? thanks

**Comment by Duankaiwen** [comment]
@wudi00 Hi, please see this issue:[princeton-vl/CornerNet#73](https://github.com/princeton-vl/CornerNet/issues/73)
