### ISSUE TITLE
Testing or Exporting without NVIDIA/CUDA?

### ISSUE THREAD

**Issue by Noltibus** [Duankaiwen/CenterNet#18]
Is it possible to test the trained model without having an NVIDIA graphics card and CUDA installed? Or even better to somehow export the trained model in a format like `.pb`? 

I tried to evaluate the trained model and I get the message: `Cuda driver version is insufficient for CUDA runtime version`. This is obvious because I don't have an NVIDIA graphics card and therefore no CUDA installed.

**Comment by Duankaiwen** [comment]
@Noltibus Sorry, our current implementation only supports GPU so you need a GPU and need to have CUDA installed on your machine
