### ISSUE TITLE
A question about center pooling

### ISSUE THREAD

**Issue by 978326187** [Duankaiwen/CenterNet#23]
![1556953904(1)](https://user-images.githubusercontent.com/29019279/57175565-3379cb80-6e80-11e9-8904-d95d745a0f92.jpg)

**Comment by Duankaiwen** [comment]
你好，会有这种情况发生，但是 Cneter 是起辅助作用的，先用两个角点生成框，再利用中心点抑制错误框。具体流程如下：两个角点生成框，在框的中心区域查看是否有Center，若有则保留，若无则删除。除非A点恰好出现在了这个框的中心区域，否则A是不会对检测结果有影响的。

**Comment by 978326187** [comment]
好的，谢谢解答
