### ISSUE TITLE
Why is the test result incorrect?

### ISSUE THREAD

**Issue by jqxxhznu** [Duankaiwen/CenterNet#25]
I used the trained model:
`python test.py CenterNet-104 --testiter 480000 --split <split>`
and get a file  result.json,but when I try to draw the detection box through bbox use opencv,I had problems.
`  cv.rectangle(src, (int(bbox[0]), int(bbox[1])), (int(bbox[2]), int(bbox[3])), (0, 255,0),1)`
![Screenshot from 2019-05-05 19-34-12](https://user-images.githubusercontent.com/43376211/57193370-d871d280-6f6c-11e9-91c8-ce5fcbf6ac05.png)
`{"image_id": 466319, "category_id": 1, "bbox": [199.02, 90.37, 135.19, 336.08], "score": 0.94}`
could you tell me the meaning of four parameters in bbox?

**Comment by Duankaiwen** [comment]
Hi @jqxxhznu, bbox[2] and bbox[3] in result.json denote the width and the height, respectivaly.

**Comment by liuzehao** [comment]
> Hi @jqxxhznu, bbox[2] and bbox[3] in result.json denote the width and the height, respectivaly.

Thank you. I've solved the problem.
