### ISSUE TITLE
What is the difference of CenterNet-52.json and CenterNet-104.json

### ISSUE THREAD

**Issue by xiaozhuka** [Duankaiwen/CenterNet#29]
@Duankaiwen 
Thanks for your excellent work. I have two questions.

1. What is the difference of CenterNet-52.json and CenterNet-104.json
![image](https://user-images.githubusercontent.com/6336709/57268406-365e0180-70b6-11e9-86cd-27b1eb478dd8.png)
2. How and where to specify Hourglass52 backbone and hourglass 104 backbone?

Thanks again. 
Best Wishes.

**Comment by Duankaiwen** [comment]
@xiaozhuka Hi, their json files are the same. The differences lie in line 135 in the models/CenterNet-104.py (CenterNet-104.py), 2 denotes 104 and 1 denotes 52.

**Comment by xiaozhuka** [comment]
@Duankaiwen Thank you
