### ISSUE TITLE
pull loss and push loss

### ISSUE THREAD

**Issue by 404289680** [Duankaiwen/CenterNet#31]

**Comment by 404289680** [comment]
what does pull loss and push loss mean

**Comment by Duankaiwen** [comment]
@404289680 Hi, the pull loss tries to make the distances of embeddings for top-left corner and bottom-right corner from the same object samll; the push loss  tries to make the distances of embeddings for top-left corners and bottom-right corners from different objects large. For more details, please refer to [CornerNet](https://arxiv.org/abs/1808.01244).
