### ISSUE TITLE
请问没有使用正常的 Conv layer 而不是 Deformable 的测试结果呢？

### ISSUE THREAD

**Issue by kzjeef** [Duankaiwen/CenterNet#40]
Hi， 

CenterNet 的速度和精度都非常棒， 先点个赞。 

由于 Deformable 卷积在代码实现层面无法使用例如 TensorCore 之类的加速指令， 所以在实际部署中， 速度是没有普通的Conv 运行的快的。 所以我想请教下 @Duankaiwen 有没有使用普通的卷积 OP把 CenterNet 的框架结合起来的想法？

不知道精度和速度会是怎么样的。

谢谢。

**Comment by Duankaiwen** [comment]
@kzjeef  Hi, we don't use deformable conv.
