### ISSUE TITLE
How to visualize the model

### ISSUE THREAD

**Issue by wudi00** [Duankaiwen/CenterNet#48]
How to visualize network structure？How to print network structure？I can't find the loading model in any of the files.

**Comment by Duankaiwen** [comment]
In line 127 in nnet/py_factory.py

**Comment by wudi00** [comment]
@Duankaiwen The input images are all resize to 512*512, but my images are 800*1216, how are they resized to square size? If the long side is 512, the short side is 337. Did I use the padding on the short side?
