### ISSUE TITLE
Could you explan more about Cascade corner pooling module?

### ISSUE THREAD

**Issue by wtiandong** [Duankaiwen/CenterNet#52]
Hi @Duankaiwen ,
I'm reading your paper now, and little confused about the cascade corner pooling layer. You say "_It first looks along a boundary to find a boundary maximum value, then looks inside along the location of the boundary maximum value to find a internal maximum value, and finally, add the two maximum values together. By doing this, the corners obtain both the the boundary information and the visual patterns of objects._"
I read your code and match it to your figure 5(b) architecture exactly. But I don't really understand this arch.  I can understand _It first looks along a boundary to find a boundary maximum value_, e.g. left pooling,  this is same as CornerNet. But how _it looks inside along the location of the boundary maximum value to find a internal maximum value, and finally, add the two maximum values together_ via 3x3-Conv and top pooling?

Thanks.

**Comment by Duankaiwen** [comment]
Hi@wtiandong,  it actually fist looks inside to find a internal maximum value for each pixel and add the internal maximum value into the feature map, and via a 3x3-Conv. We think this step equips each pixel with internal feature. Then it along a boundary to find a boundary maximum value. We think the this boundary maximum value also has the internal feature.

**Comment by wtiandong** [comment]
> Hi@wtiandong, it actually fist looks inside to find a internal maximum value for each pixel and add the internal maximum value into the feature map, and via a 3x3-Conv. We think this step equips each pixel with internal feature. Then it looks along a boundary to find a boundary maximum value. We think the this boundary maximum value also has the internal feature.

OK. It's clear now. Thank you very much.
