### ISSUE TITLE
Only one GPU  setting error!

### ISSUE THREAD

**Issue by ghost** [Duankaiwen/CenterNet#60]
Hey,Dear Author!
My computer only one GPU(1070Ti) !  How about set ".json" file **chunk_size** and **batch_size** in config?

**Comment by MKMikeGao** [comment]
I setting `"batch_size":1` and `"chunk_size": [1]` in .json file

**Comment by yangwithtao** [comment]
hello，
when I setting "batch_size":1 and "chunk_size": [1] in .json file，It will report an error:
`RuntimeError: Dimension out of range (expected to be in range of [-2, 1], but got 2)`
what problem？
Thanks
