### ISSUE TITLE
inference speed

### ISSUE THREAD

**Issue by arc144** [Duankaiwen/CenterNet#61]
Hi! First of all thanks for the paper and implementation.

In the paper you mention:
>  CenterNet,  with both center pooling and cascade corner pooling incorporated, reports an AP of 47.0% on the test-dev set, which outperforms all existing one-stage detectors by a large margin. With an average inference time of 270ms using a 52-layer hourglass back-bone  [29]  and 340ms using  a  104-layer  hourglass  back-bone [29] per image, CenterNet is quite efficient yet closely matches the state-of-the-art performance of the other two-stage detectors.

The inference time you reported is using multi-scale or single-scale setup? I know it is usual to report the single scale time but from your paper it seems you are talking about multi-scale. 

Thanks

**Comment by Duankaiwen** [comment]
@arc144 Hi, the inference time is using single-scale setup
