### ISSUE TITLE
issues about the db config

### ISSUE THREAD

**Issue by runzeer** [Duankaiwen/CenterNet#63]
In the db filefolder, there exists the detection.py. In this file, I find some configs which are similar to the mmdetection ,which is a object detection framework. But I did not find the usage of the config such as "bbox_head" , "bbox_roi_extractor" and the train_cfg['rcnn']. So are they used in your codes?  Or you just want to reimplement the code in the mmdetection framework?

**Comment by Duankaiwen** [comment]
@runzeer Hi, they are not used. Just ignore it.
