### ISSUE TITLE
用自己的数据集训练需要改哪些参数？

### ISSUE THREAD

**Issue by Lily1992** [Duankaiwen/CenterNet#67]
您好。用自己的数据训练，除了要改这些参数：
#out_dim in CenterNet-104.py,
    #categories in CornerNet.json
    #self._configs[“categories”] in detection.py.
    #   coco.py---     self._cat_ids

是不是以下两处的参数也需要改呢？
train.py中的 for iteration in tqdm(range(start_iter + 1, max_iteration + 1), file=save_stdout, ncols=80): 的ncols =80 
db/detection.py 中的 num_classes=81,

**Comment by Duankaiwen** [comment]
@Lily1992 你好，ncols 不需要改，num_classes需要改

**Comment by Lily1992** [comment]
好的，谢谢。
