### ISSUE TITLE
训练时发生死锁的问题

### ISSUE THREAD

**Issue by lizhe960118** [Duankaiwen/CenterNet#70]
ctrl+c之后，发现程序停在
```
training = pinned_training_queue.get(block=True)
self.not_empty.wait()
waiter.acquire()
```
能正常测试，怎么解决？

**Comment by yangwithtao** [comment]
Failed to get the sample, waiting for the incoming sample to have a similar problem

**Comment by lizhe960118** [comment]
@yangwithtao how can i slove this problem?

**Comment by yangwithtao** [comment]
The same problem I encountered: using my own sample data is not COCO, the incoming format is wrong, another thread receiving data has been waiting for data, and when I ended the process I found the same error as you.

If you are using a COCO dataset, you need to check the images and annotations are correct.
If you want to train your own data like me, you can make your data into COCO format，or  view the training format of the sample data and modify your sample input method.

**Comment by lizhe960118** [comment]
@yangwithtao thank you very much! i have checked the coco.py in sample, and find some cv2 function don't not work in my machine, so i modified the function. It's the problem about reading data, now i can train my code. It's a pleasure to communicate with you.
