### ISSUE TITLE
训练自己的数据集--数据预处理参数

### ISSUE THREAD

**Issue by 201901** [Duankaiwen/CenterNet#72]
@Duankaiwen   你好！请问如果我使用自己的数据集训练，在 /db/coco.py下的这些数据预处理的参数要不要更新？
 /db/coco.py
        ......
        self._mean = np.array([0.40789654, 0.44719302, 0.47026115], dtype=np.float32)
        self._std  = np.array([0.28863828, 0.27408164, 0.27809835], dtype=np.float32)
        self._eig_val = np.array([0.2141788, 0.01817699, 0.00341571], dtype=np.float32)
        self._eig_vec = np.array([
            [-0.58752847, -0.69563484, 0.41340352],
            [-0.5832747, 0.00994535, -0.81221408],
            [-0.56089297, 0.71832671, 0.41158938]
      .......

**Comment by ZhWL123456** [comment]
要把~ 你知道那个特征值和特征向量怎么计算嘛
