### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Dawnlnz** [Duankaiwen/CenterNet#74]
When I want to run train.py file, I meet the follow error:
Traceback (most recent call last):
  File "train.py", line 198, in <module>
    validation_db = datasets[dataset](configs["db"], val_split)
  File "/home/b08/projects/CenterNet_keypoints/db/coco.py", line 67, in __init__
    self._load_data()
  File "/home/b08/projects/CenterNet_keypoints/db/coco.py", line 84, in _load_data
    self._detections, self._image_ids = pickle.load(f)
TypeError: 'int' object is not iterable

**Comment by Duankaiwen** [comment]
@Dawnlnz Which version of python do you use？

**Comment by Dawnlnz** [comment]
Python 3.6




| |
18281575602
邮箱：18281575602@163.com
|

Signature is customized by Netease Mail Master

On 07/25/2019 18:39, Kaiwen Duan wrote:

@Dawnlnz Which version of python do you use？

**Comment by Dawnlnz** [comment]
I still haven't solved this bug,can you help me?

**Comment by Duankaiwen** [comment]
Make sure the path 'self._cache_file' exist and the file in ‘self._cache_file’ is correct

**Comment by Dawnlnz** [comment]
@Duankaiwen  Thank you for your reply. I solved the problem with your help

**Comment by Duankaiwen** [comment]
@Dawnlnz You're welcome
