### ISSUE TITLE
Configuration understanding

### ISSUE THREAD

**Issue by ruinianxu** [Duankaiwen/CenterNet#77]
Hi Duankaiwen,
I'd like to modified your work for my own use and I have some confusions about parameters in the config. 
First, does "output_sizes" mean that resizing original input image into that size specified? Is 128 too small? Or if I want to keep the size, I just need to let the output size to be the same as input size?
Second, does "max_per_image" mean the maximal number of instances in one image? I still met the error about index exceed even I change the parameter within kp_detectiion to be some value like 500 while I don't think there is any image includes over 500 bounding boxes. So right now, I just choose first max_per_image instances after shuffling. 
Really appreciate it if you can give me some hints.

**Comment by ruinianxu** [comment]
I think I have understood the meaning of 128, which should be the size of heatmap actually.

**Comment by Duankaiwen** [comment]
@ruinianxu Hi, the output_size is the heatmap, and output_size = resized original input image/4.
 "max_per_image" means select top 'max_per_image' boxes for each image as the final results.
