### ISSUE TITLE
Add demo.py

### ISSUE THREAD

**Issue by murdockhou** [Duankaiwen/CenterNet#8]
Hi, thanks for your work. Can you give one `demo.py` file that can used trained model in images/video/web camera? Thanks a lot.

**Comment by Duankaiwen** [comment]
Use python test.py CenterNet-104 --testiter 480000 --split <split> --debug

**Comment by murdockhou** [comment]
no use for the command line that you provided.

**Comment by Duankaiwen** [comment]
@murdockhou Can I see your log?

**Comment by vusraju** [comment]
@Duankaiwen , by using the command "python test.py CenterNet-104 --testiter 480000 --split --debug", How can I input an image that has to be tested? because the command is not taking any input image path
