### ISSUE TITLE
Success train model on cuda10

### ISSUE THREAD

**Issue by lyyiangang** [Duankaiwen/CenterNet#91]
I tried to make the training code run in the past 3 days, and paid a lot of efforts. Finally, make the train code work on my machine. I think it's necessary make an issue here help more users.
My environment:
```
Ubuntu: 16.04
python: 3.6
pytorch:1.2.0
GPU: 4 T2080ti
CUDA:10.0
```
1. remove the _cptools folder first.
```
cd centernet_dir/models/py_utils/
rm -rf _cpools/ 
```
2. copy a new _cptools foler from https://github.com/princeton-vl/CornerNet-Lite/tree/master/core/models/py_utils/_cpools and place it to your centernet_dir/models/py_utils

3. install docker and [nvidia-docker](https://github.com/NVIDIA/nvidia-docker) first.
4. copy the docker file from [here](https://github.com/lyyiangang/dockerfiles/blob/master/pytorch_test.dockerfile) and build your own image:
  ``` docker build -f ./pytorch_test.dockerfile -t pytorch_v2 --build-arg USERID=$(id -u) .```
5. run the docker container
```
xhost +local:${USER}
docker run --gpus all -it  --rm -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix  -v /home/VOCDataset:/project/VOCDataset  -u $(id -u):$(id -g) --ipc host pytorch_v2
```
you need map the voc dataset to your container and map there to the right places follow this  repo's readme.
6. compile corner pooling layers:
```
cd models/py_utils/_cpools/
python3.6 setup.py install --user
```
7. compiling NMS
```
cd exteranl
python3.6 setup.py build_ext --inplace
```
note, since we have install cocoapi in docker file, see 
```
RUN python3.6 -m pip install "git+https://github.com/philferriere/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI"
```
you don't have to install again.
8. modify the CenterNet-104.json
```
"batch_size" : 2,
"chunk_sizes":[2],
```
the length of chunk_sizes should be less than your gpu count. If you want to use 3 gpus, you can set like this:
```
"batch_size":6,
"chunk_sizes":[2, 2, 2],
```
9, run the train script.
```
python3.6 train.py CenterNet-104
```

**Comment by mochechan** [comment]
Thank you. I appreciated your time and effort. 
Another method to train model on cuda10 is to use [Cornernet_Lite's conda_packagelist.txt](https://github.com/princeton-vl/CornerNet-Lite#installing-dependencies).

**Comment by Zhao-hangtian** [comment]
Thank you every much :+1:
